server:
  port: 5000
spring:
  application:
    name: Auth-Service
registry:
  address: http://localhost:8000
# ROTATION：轮训、RANDOM：随机、AVAILABLE：高可用
service:
  discovery:
    strategy: AVAILABLE