server:
  port: 9000
spring:
  application:
    name: Log-Service
log:
  file:
    path: distributed.log
registry:
  address: http://localhost:8000
# ROTATION：轮训、RANDOM：随机、AVAILABLE：高可用
service:
  discovery:
    strategy: AVAILABLE